### ISSUE TITLE
No such module 'Navajo_Swift'

### ISSUE THREAD

**Issue by ghost** [peterfriese/SwiftUI-Combine#2]
Hi Peter,
I'm new to Swift development and Xcode (I use last Xcode 11.4.1) and I get a build error:
`SwiftUI-Combine-master/SwiftUI-Combine/ViewModels/UserViewModel.swift:11:8: No such module 'Navajo_Swift' `

I have tried to add a "Framework Search Paths"  to $(SRCROOT) and set it to recursive but without success ([https://stackoverflow.com/questions/29500227/getting-error-no-such-module-using-xcode-but-the-framework-is-there](url)

Can you help me to resolve this build issue ?

Thanks

**Comment by peterfriese** [comment]
Hi Jean,

did you run `pod install` after cloning the repo?

Feel free to post a list of steps you followed here so I can see where things break for you.

Cheers,
Peter

**Comment by ghost** [comment]
Hi Peter,

sank you for your fast response, I though I had done `pod intall`, but now I have cloned your git again and installed the pods and now it works !
Danke !

Jean G.

**Comment by peterfriese** [comment]
Great, thanks for letting me know!
